// Code generated by goyacc -p expr -o pkg/logql/expr.y.go pkg/logql/expr.y. DO NOT EDIT.

//line pkg/logql/expr.y:2
package logql

import __yyfmt__ "fmt"

//line pkg/logql/expr.y:2

import (
	"github.com/prometheus/prometheus/pkg/labels"
	"github.com/ronanh/loki/pkg/logql/log"
	"time"
)

//line pkg/logql/expr.y:12
type exprSymType struct {
	yys                   int
	Expr                  Expr
	Filter                labels.MatchType
	Grouping              *grouping
	Labels                []string
	LogExpr               LogSelectorExpr
	LogRangeExpr          *logRange
	Matcher               *labels.Matcher
	Matchers              []*labels.Matcher
	RangeAggregationExpr  SampleExpr
	RangeOp               string
	ConvOp                string
	Selector              []*labels.Matcher
	VectorAggregationExpr SampleExpr
	MetricExpr            SampleExpr
	VectorOp              string
	BinOpExpr             SampleExpr
	LabelReplaceExpr      SampleExpr
	binOp                 string
	bytes                 uint64
	str                   string
	duration              time.Duration
	LiteralExpr           *literalExpr
	BinOpModifier         BinOpOptions
	LabelParser           *labelParserExpr
	LineFilters           *lineFilterExpr
	PipelineExpr          MultiStageExpr
	PipelineStage         StageExpr
	BytesFilter           log.LabelFilterer
	NumberFilter          log.LabelFilterer
	DurationFilter        log.LabelFilterer
	LabelFilter           log.LabelFilterer
	UnitFilter            log.LabelFilterer
	LineFormatExpr        *lineFmtExpr
	LabelFormatExpr       *labelFmtExpr
	LabelFormat           log.LabelFmt
	LabelsFormat          []log.LabelFmt
	JSONExpressionParser  *jsonExpressionParser
	JSONExpression        log.JSONExpression
	JSONExpressionList    []log.JSONExpression
	UnwrapExpr            *unwrapExpr
	DropLabel             log.DropLabel
	DropLabels            []log.DropLabel
	DropLabelsExpr        *DropLabelsExpr
}

const BYTES = 57346
const IDENTIFIER = 57347
const STRING = 57348
const NUMBER = 57349
const DURATION = 57350
const RANGE = 57351
const MATCHERS = 57352
const LABELS = 57353
const EQ = 57354
const RE = 57355
const NRE = 57356
const OPEN_BRACE = 57357
const CLOSE_BRACE = 57358
const OPEN_BRACKET = 57359
const CLOSE_BRACKET = 57360
const COMMA = 57361
const DOT = 57362
const PIPE_MATCH = 57363
const PIPE_EXACT = 57364
const OPEN_PARENTHESIS = 57365
const CLOSE_PARENTHESIS = 57366
const BY = 57367
const WITHOUT = 57368
const COUNT_OVER_TIME = 57369
const RATE = 57370
const SUM = 57371
const AVG = 57372
const MAX = 57373
const MIN = 57374
const COUNT = 57375
const STDDEV = 57376
const STDVAR = 57377
const BOTTOMK = 57378
const TOPK = 57379
const BYTES_OVER_TIME = 57380
const BYTES_RATE = 57381
const BOOL = 57382
const JSON = 57383
const REGEXP = 57384
const LOGFMT = 57385
const PATTERN = 57386
const PIPE = 57387
const LINE_FMT = 57388
const LABEL_FMT = 57389
const UNWRAP = 57390
const AVG_OVER_TIME = 57391
const SUM_OVER_TIME = 57392
const MIN_OVER_TIME = 57393
const MAX_OVER_TIME = 57394
const STDVAR_OVER_TIME = 57395
const STDDEV_OVER_TIME = 57396
const QUANTILE_OVER_TIME = 57397
const BYTES_CONV = 57398
const DURATION_CONV = 57399
const DURATION_SECONDS_CONV = 57400
const ABSENT_OVER_TIME = 57401
const LABEL_REPLACE = 57402
const UNPACK = 57403
const DROP = 57404
const OR = 57405
const AND = 57406
const UNLESS = 57407
const CMP_EQ = 57408
const NEQ = 57409
const LT = 57410
const LTE = 57411
const GT = 57412
const GTE = 57413
const ADD = 57414
const SUB = 57415
const MUL = 57416
const DIV = 57417
const MOD = 57418
const POW = 57419

var exprToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"BYTES",
	"IDENTIFIER",
	"STRING",
	"NUMBER",
	"DURATION",
	"RANGE",
	"MATCHERS",
	"LABELS",
	"EQ",
	"RE",
	"NRE",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_BRACKET",
	"CLOSE_BRACKET",
	"COMMA",
	"DOT",
	"PIPE_MATCH",
	"PIPE_EXACT",
	"OPEN_PARENTHESIS",
	"CLOSE_PARENTHESIS",
	"BY",
	"WITHOUT",
	"COUNT_OVER_TIME",
	"RATE",
	"SUM",
	"AVG",
	"MAX",
	"MIN",
	"COUNT",
	"STDDEV",
	"STDVAR",
	"BOTTOMK",
	"TOPK",
	"BYTES_OVER_TIME",
	"BYTES_RATE",
	"BOOL",
	"JSON",
	"REGEXP",
	"LOGFMT",
	"PATTERN",
	"PIPE",
	"LINE_FMT",
	"LABEL_FMT",
	"UNWRAP",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"STDVAR_OVER_TIME",
	"STDDEV_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"BYTES_CONV",
	"DURATION_CONV",
	"DURATION_SECONDS_CONV",
	"ABSENT_OVER_TIME",
	"LABEL_REPLACE",
	"UNPACK",
	"DROP",
	"OR",
	"AND",
	"UNLESS",
	"CMP_EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}

var exprStatenames = [...]string{}

const exprEofCode = 1
const exprErrCode = 2
const exprInitialStackSize = 16

//line pkg/logql/expr.y:397

//line yacctab:1
var exprExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const exprPrivate = 57344

const exprLast = 469

var exprAct = [...]int16{
	73, 189, 4, 108, 170, 56, 160, 167, 155, 64,
	55, 198, 15, 5, 129, 48, 69, 66, 2, 239,
	12, 43, 44, 45, 46, 47, 48, 242, 6, 59,
	265, 282, 19, 20, 31, 32, 34, 35, 33, 36,
	37, 38, 39, 21, 22, 45, 46, 47, 48, 80,
	238, 74, 75, 296, 23, 24, 25, 26, 27, 28,
	29, 95, 115, 292, 30, 18, 239, 99, 125, 127,
	128, 72, 280, 74, 75, 133, 157, 16, 17, 240,
	111, 138, 62, 188, 62, 131, 239, 96, 62, 60,
	61, 60, 61, 287, 273, 60, 61, 139, 243, 140,
	141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
	151, 152, 153, 191, 185, 191, 275, 251, 172, 191,
	164, 156, 253, 126, 251, 115, 200, 180, 211, 252,
	115, 266, 62, 249, 194, 63, 262, 63, 196, 60,
	61, 63, 190, 111, 157, 202, 192, 193, 111, 201,
	40, 41, 42, 49, 50, 53, 54, 51, 52, 43,
	44, 45, 46, 47, 48, 204, 205, 206, 41, 42,
	49, 50, 53, 54, 51, 52, 43, 44, 45, 46,
	47, 48, 268, 269, 270, 63, 185, 234, 158, 156,
	236, 115, 241, 185, 244, 247, 95, 120, 248, 237,
	99, 131, 235, 245, 62, 157, 119, 294, 246, 111,
	209, 60, 61, 200, 255, 186, 172, 261, 257, 49,
	50, 53, 54, 51, 52, 43, 44, 45, 46, 47,
	48, 291, 199, 240, 137, 58, 130, 136, 62, 263,
	173, 127, 128, 95, 12, 60, 61, 274, 264, 158,
	156, 95, 132, 276, 115, 135, 265, 63, 197, 12,
	78, 71, 278, 279, 250, 212, 12, 132, 157, 191,
	124, 285, 111, 281, 6, 210, 286, 207, 19, 20,
	31, 32, 34, 35, 33, 36, 37, 38, 39, 21,
	22, 63, 239, 203, 179, 174, 177, 178, 175, 176,
	23, 24, 25, 26, 27, 28, 29, 238, 195, 134,
	30, 18, 187, 208, 290, 284, 217, 12, 182, 218,
	216, 77, 272, 16, 17, 6, 283, 115, 271, 19,
	20, 31, 32, 34, 35, 33, 36, 37, 38, 39,
	21, 22, 76, 239, 214, 111, 181, 215, 213, 259,
	260, 23, 24, 25, 26, 27, 28, 29, 115, 109,
	295, 30, 18, 103, 105, 104, 106, 188, 112, 113,
	242, 293, 62, 122, 16, 17, 111, 289, 232, 60,
	61, 233, 231, 107, 114, 79, 3, 121, 229, 288,
	123, 230, 228, 65, 103, 105, 104, 106, 226, 112,
	113, 227, 225, 191, 223, 256, 220, 224, 222, 221,
	219, 254, 184, 258, 107, 114, 168, 159, 183, 182,
	181, 165, 163, 162, 154, 63, 118, 81, 82, 83,
	84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
	94, 68, 277, 171, 70, 161, 70, 168, 98, 166,
	101, 100, 169, 102, 57, 116, 110, 117, 97, 11,
	10, 9, 14, 8, 267, 13, 7, 67, 1,
}

var exprPact = [...]int16{
	5, -1000, 87, -1000, -1000, 190, 5, -1000, -1000, -1000,
	-1000, -1000, 439, 238, 48, -1000, 335, 314, 237, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
	9, 9, 9, 9, 9, 190, -1000, 118, 353, 420,
	-1000, -1000, -1000, -1000, 182, 173, 87, 371, 254, -1000,
	56, 229, 302, 232, 214, 211, -1000, -1000, 5, 5,
	-1000, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, -1000, 418, -1000, -1000, 125,
	-1000, -1000, -1000, 440, -1000, 417, 416, -1000, -1000, -1000,
	-1000, 120, 415, 442, 438, 228, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 441, -1000, 414, 413, 412, 406, 191,
	293, 358, 244, 110, 289, 251, 208, 121, 274, 104,
	153, 153, -29, -29, -62, -62, -62, -62, -51, -51,
	-51, -51, -51, -51, -1000, 125, 120, 120, 120, 258,
	-1000, 301, -1000, -1000, 186, -1000, 256, -1000, 116, 246,
	-1000, 56, -1000, 340, 312, 402, 400, 394, 384, 374,
	-1000, -1000, -1000, -1000, -1000, -1000, 26, 244, 68, 41,
	224, 322, 74, 184, 26, 5, 109, 245, 105, -1000,
	-1000, 98, -1000, 405, 249, 125, 57, 440, 399, -1000,
	411, 344, 438, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 112, -26, 68, -1000, 120,
	-1000, 21, 126, 319, 298, 70, -1000, -1000, 92, -1000,
	5, 437, -1000, -1000, 243, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 26, -26, 125, -1000, -1000, 49, -1000, -1000,
	-1000, -14, 317, 306, 247, 26, 69, -1000, 383, -1000,
	372, -26, -21, -1000, -1000, 305, -1000, -1000, 212, 39,
	-1000, 365, -1000, 188, 354, 29, -1000,
}

var exprPgo = [...]int16{
	0, 468, 17, 29, 0, 11, 386, 2, 14, 3,
	467, 466, 465, 464, 13, 463, 462, 461, 460, 459,
	385, 458, 10, 5, 457, 456, 455, 8, 454, 453,
	452, 4, 451, 450, 7, 449, 448, 6, 417, 1,
	359,
}

var exprR1 = [...]int8{
	0, 1, 2, 2, 7, 7, 7, 7, 7, 7,
	6, 6, 6, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 39, 39, 39,
	13, 13, 13, 11, 11, 11, 11, 15, 15, 15,
	15, 15, 15, 19, 3, 3, 3, 3, 14, 14,
	14, 10, 10, 9, 9, 9, 9, 22, 22, 23,
	23, 23, 23, 23, 23, 23, 28, 28, 21, 21,
	21, 21, 21, 36, 32, 34, 34, 35, 35, 35,
	33, 27, 27, 27, 27, 27, 27, 27, 27, 37,
	38, 38, 40, 40, 26, 26, 26, 26, 26, 26,
	26, 24, 24, 24, 24, 24, 24, 24, 25, 25,
	25, 25, 25, 25, 25, 31, 31, 30, 30, 29,
	17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
	17, 17, 17, 17, 17, 20, 20, 18, 18, 18,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 5, 5, 4, 4, 4, 4,
}

var exprR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	1, 2, 3, 2, 4, 3, 5, 3, 5, 3,
	5, 4, 6, 3, 4, 3, 2, 3, 6, 3,
	1, 1, 1, 4, 6, 5, 7, 4, 5, 5,
	6, 7, 7, 12, 1, 1, 1, 1, 3, 3,
	3, 1, 3, 3, 3, 3, 3, 1, 2, 1,
	2, 2, 2, 2, 2, 2, 2, 3, 1, 1,
	2, 2, 1, 2, 2, 3, 3, 1, 3, 3,
	2, 1, 1, 1, 3, 2, 3, 3, 3, 3,
	1, 3, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 1, 1, 1, 3, 2,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 0, 1, 1, 2, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 4, 4, 3, 3,
}

var exprChk = [...]int16{
	-1000, -1, -2, -6, -7, -14, 23, -11, -15, -17,
	-18, -19, 15, -12, -16, 7, 72, 73, 60, 27,
	28, 38, 39, 49, 50, 51, 52, 53, 54, 55,
	59, 29, 30, 33, 31, 32, 34, 35, 36, 37,
	63, 64, 65, 72, 73, 74, 75, 76, 77, 66,
	67, 70, 71, 68, 69, -22, -23, -28, 45, -3,
	21, 22, 14, 67, -7, -6, -2, -10, 2, -9,
	5, 23, 23, -4, 25, 26, 7, 7, 23, -20,
	40, -20, -20, -20, -20, -20, -20, -20, -20, -20,
	-20, -20, -20, -20, -20, -23, -3, -21, -36, -27,
	-32, -33, -29, 41, 43, 42, 44, 61, -9, -40,
	-25, 23, 46, 47, 62, 5, -26, -24, 6, 24,
	24, 16, 2, 19, 16, 12, 67, 13, 14, -8,
	7, -14, 23, -7, 7, 23, 23, 23, -7, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, 6, -27, 64, 19, 63, -38,
	-37, 5, 6, 6, -27, 6, -35, -34, 5, -30,
	-31, 5, -9, 12, 67, 70, 71, 68, 69, 66,
	-9, 6, 6, 6, 6, 2, 24, 19, 9, -39,
	-22, 45, -14, -8, 24, 19, -7, 7, -5, 24,
	5, -5, 24, 19, -27, -27, -27, 19, 12, 24,
	19, 12, 19, 8, 4, 7, 8, 4, 7, 8,
	4, 7, 8, 4, 7, 8, 4, 7, 8, 4,
	7, 8, 4, 7, -4, -8, -39, -22, 9, 45,
	9, -39, 48, 24, -39, -22, 24, -4, -7, 24,
	19, 19, 24, 24, 6, -37, 6, -34, 2, 5,
	6, -31, 24, -39, -27, 9, 5, -13, 56, 57,
	58, 9, 24, 24, -39, 24, -7, 5, 19, -4,
	23, -39, 45, 9, 9, 24, -4, 24, 6, 5,
	9, 19, 24, 6, 19, 6, 24,
}

var exprDef = [...]int16{
	0, -2, 1, 2, 3, 10, 0, 4, 5, 6,
	7, 8, 0, 0, 0, 137, 0, 0, 0, 149,
	150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
	160, 140, 141, 142, 143, 144, 145, 146, 147, 148,
	135, 135, 135, 135, 135, 135, 135, 135, 135, 135,
	135, 135, 135, 135, 135, 11, 57, 59, 0, 0,
	44, 45, 46, 47, 3, 2, 0, 0, 0, 51,
	0, 0, 0, 0, 0, 0, 138, 139, 0, 0,
	136, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 58, 0, 60, 61, 62,
	63, 64, 65, 68, 69, 0, 0, 72, 81, 82,
	83, 0, 0, 0, 0, 0, 92, 93, 66, 9,
	12, 48, 49, 0, 50, 0, 0, 0, 0, 0,
	0, 0, 0, 3, 137, 0, 0, 0, 3, 120,
	121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
	131, 132, 133, 134, 67, 85, 0, 0, 0, 73,
	90, 0, 70, 71, 0, 74, 80, 77, 0, 119,
	117, 115, 116, 0, 0, 0, 0, 0, 0, 0,
	52, 53, 54, 55, 56, 26, 33, 0, 13, 0,
	0, 0, 0, 0, 37, 0, 3, 137, 0, 165,
	161, 0, 166, 0, 86, 87, 88, 0, 0, 84,
	0, 0, 0, 99, 106, 113, 98, 105, 112, 94,
	101, 108, 95, 102, 109, 96, 103, 110, 97, 104,
	111, 100, 107, 114, 35, 0, 15, 23, 17, 0,
	19, 0, 0, 0, 0, 0, 25, 39, 3, 38,
	0, 0, 163, 164, 0, 91, 89, 78, 79, 75,
	76, 118, 34, 24, 29, 21, 27, 0, 30, 31,
	32, 14, 0, 0, 0, 40, 3, 162, 0, 36,
	0, 16, 0, 18, 20, 0, 41, 42, 0, 0,
	22, 0, 28, 0, 0, 0, 43,
}

var exprTok1 = [...]int8{
	1,
}

var exprTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77,
}

var exprTok3 = [...]int8{
	0,
}

var exprErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	exprDebug        = 0
	exprErrorVerbose = false
)

type exprLexer interface {
	Lex(lval *exprSymType) int
	Error(s string)
}

type exprParser interface {
	Parse(exprLexer) int
	Lookahead() int
}

type exprParserImpl struct {
	lval  exprSymType
	stack [exprInitialStackSize]exprSymType
	char  int
}

func (p *exprParserImpl) Lookahead() int {
	return p.char
}

func exprNewParser() exprParser {
	return &exprParserImpl{}
}

const exprFlag = -1000

func exprTokname(c int) string {
	if c >= 1 && c-1 < len(exprToknames) {
		if exprToknames[c-1] != "" {
			return exprToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func exprStatname(s int) string {
	if s >= 0 && s < len(exprStatenames) {
		if exprStatenames[s] != "" {
			return exprStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func exprErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !exprErrorVerbose {
		return "syntax error"
	}

	for _, e := range exprErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + exprTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(exprPact[state])
	for tok := TOKSTART; tok-1 < len(exprToknames); tok++ {
		if n := base + tok; n >= 0 && n < exprLast && int(exprChk[int(exprAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if exprDef[state] == -2 {
		i := 0
		for exprExca[i] != -1 || int(exprExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; exprExca[i] >= 0; i += 2 {
			tok := int(exprExca[i])
			if tok < TOKSTART || exprExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if exprExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += exprTokname(tok)
	}
	return res
}

func exprlex1(lex exprLexer, lval *exprSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(exprTok1[0])
		goto out
	}
	if char < len(exprTok1) {
		token = int(exprTok1[char])
		goto out
	}
	if char >= exprPrivate {
		if char < exprPrivate+len(exprTok2) {
			token = int(exprTok2[char-exprPrivate])
			goto out
		}
	}
	for i := 0; i < len(exprTok3); i += 2 {
		token = int(exprTok3[i+0])
		if token == char {
			token = int(exprTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(exprTok2[1]) /* unknown char */
	}
	if exprDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", exprTokname(token), uint(char))
	}
	return char, token
}

func exprParse(exprlex exprLexer) int {
	return exprNewParser().Parse(exprlex)
}

func (exprrcvr *exprParserImpl) Parse(exprlex exprLexer) int {
	var exprn int
	var exprVAL exprSymType
	var exprDollar []exprSymType
	_ = exprDollar // silence set and not used
	exprS := exprrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	exprstate := 0
	exprrcvr.char = -1
	exprtoken := -1 // exprrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		exprstate = -1
		exprrcvr.char = -1
		exprtoken = -1
	}()
	exprp := -1
	goto exprstack

ret0:
	return 0

ret1:
	return 1

exprstack:
	/* put a state and value onto the stack */
	if exprDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", exprTokname(exprtoken), exprStatname(exprstate))
	}

	exprp++
	if exprp >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprS[exprp] = exprVAL
	exprS[exprp].yys = exprstate

exprnewstate:
	exprn = int(exprPact[exprstate])
	if exprn <= exprFlag {
		goto exprdefault /* simple state */
	}
	if exprrcvr.char < 0 {
		exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
	}
	exprn += exprtoken
	if exprn < 0 || exprn >= exprLast {
		goto exprdefault
	}
	exprn = int(exprAct[exprn])
	if int(exprChk[exprn]) == exprtoken { /* valid shift */
		exprrcvr.char = -1
		exprtoken = -1
		exprVAL = exprrcvr.lval
		exprstate = exprn
		if Errflag > 0 {
			Errflag--
		}
		goto exprstack
	}

exprdefault:
	/* default state action */
	exprn = int(exprDef[exprstate])
	if exprn == -2 {
		if exprrcvr.char < 0 {
			exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if exprExca[xi+0] == -1 && int(exprExca[xi+1]) == exprstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			exprn = int(exprExca[xi+0])
			if exprn < 0 || exprn == exprtoken {
				break
			}
		}
		exprn = int(exprExca[xi+1])
		if exprn < 0 {
			goto ret0
		}
	}
	if exprn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			exprlex.Error(exprErrorMessage(exprstate, exprtoken))
			Nerrs++
			if exprDebug >= 1 {
				__yyfmt__.Printf("%s", exprStatname(exprstate))
				__yyfmt__.Printf(" saw %s\n", exprTokname(exprtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for exprp >= 0 {
				exprn = int(exprPact[exprS[exprp].yys]) + exprErrCode
				if exprn >= 0 && exprn < exprLast {
					exprstate = int(exprAct[exprn]) /* simulate a shift of "error" */
					if int(exprChk[exprstate]) == exprErrCode {
						goto exprstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if exprDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", exprS[exprp].yys)
				}
				exprp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if exprDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", exprTokname(exprtoken))
			}
			if exprtoken == exprEofCode {
				goto ret1
			}
			exprrcvr.char = -1
			exprtoken = -1
			goto exprnewstate /* try again in the same state */
		}
	}

	/* reduction by production exprn */
	if exprDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", exprn, exprStatname(exprstate))
	}

	exprnt := exprn
	exprpt := exprp
	_ = exprpt // guard against "declared and not used"

	exprp -= int(exprR2[exprn])
	// exprp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if exprp+1 >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprVAL = exprS[exprp+1]

	/* consult goto table to find next state */
	exprn = int(exprR1[exprn])
	exprg := int(exprPgo[exprn])
	exprj := exprg + exprS[exprp].yys + 1

	if exprj >= exprLast {
		exprstate = int(exprAct[exprg])
	} else {
		exprstate = int(exprAct[exprj])
		if int(exprChk[exprstate]) != -exprn {
			exprstate = int(exprAct[exprg])
		}
	}
	// dummy call; replaced with literal code
	switch exprnt {

	case 1:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:119
		{
			exprlex.(*parser).expr = exprDollar[1].Expr
		}
	case 2:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:122
		{
			exprVAL.Expr = exprDollar[1].LogExpr
		}
	case 3:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:123
		{
			exprVAL.Expr = exprDollar[1].MetricExpr
		}
	case 4:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:127
		{
			exprVAL.MetricExpr = exprDollar[1].RangeAggregationExpr
		}
	case 5:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:128
		{
			exprVAL.MetricExpr = exprDollar[1].VectorAggregationExpr
		}
	case 6:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:129
		{
			exprVAL.MetricExpr = exprDollar[1].BinOpExpr
		}
	case 7:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:130
		{
			exprVAL.MetricExpr = exprDollar[1].LiteralExpr
		}
	case 8:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:131
		{
			exprVAL.MetricExpr = exprDollar[1].LabelReplaceExpr
		}
	case 9:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:132
		{
			exprVAL.MetricExpr = exprDollar[2].MetricExpr
		}
	case 10:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:136
		{
			exprVAL.LogExpr = newMatcherExpr(exprDollar[1].Selector)
		}
	case 11:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:137
		{
			exprVAL.LogExpr = newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr)
		}
	case 12:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:138
		{
			exprVAL.LogExpr = exprDollar[2].LogExpr
		}
	case 13:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:142
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].duration, nil)
		}
	case 14:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:143
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[4].duration, nil)
		}
	case 15:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:144
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].duration, exprDollar[3].UnwrapExpr)
		}
	case 16:
		exprDollar = exprS[exprpt-5 : exprpt+1]
//line pkg/logql/expr.y:145
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[4].duration, exprDollar[5].UnwrapExpr)
		}
	case 17:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:146
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].duration, exprDollar[2].UnwrapExpr)
		}
	case 18:
		exprDollar = exprS[exprpt-5 : exprpt+1]
//line pkg/logql/expr.y:147
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[5].duration, exprDollar[3].UnwrapExpr)
		}
	case 19:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:148
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr), exprDollar[3].duration, nil)
		}
	case 20:
		exprDollar = exprS[exprpt-5 : exprpt+1]
//line pkg/logql/expr.y:149
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[2].Selector), exprDollar[3].PipelineExpr), exprDollar[5].duration, nil)
		}
	case 21:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:150
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr), exprDollar[4].duration, exprDollar[3].UnwrapExpr)
		}
	case 22:
		exprDollar = exprS[exprpt-6 : exprpt+1]
//line pkg/logql/expr.y:151
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[2].Selector), exprDollar[3].PipelineExpr), exprDollar[6].duration, exprDollar[4].UnwrapExpr)
		}
	case 23:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:152
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].PipelineExpr), exprDollar[2].duration, nil)
		}
	case 24:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:153
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].PipelineExpr), exprDollar[2].duration, exprDollar[4].UnwrapExpr)
		}
	case 25:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:154
		{
			exprVAL.LogRangeExpr = exprDollar[2].LogRangeExpr
		}
	case 27:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:159
		{
			exprVAL.UnwrapExpr = newUnwrapExpr(exprDollar[3].str, "")
		}
	case 28:
		exprDollar = exprS[exprpt-6 : exprpt+1]
//line pkg/logql/expr.y:160
		{
			exprVAL.UnwrapExpr = newUnwrapExpr(exprDollar[5].str, exprDollar[3].ConvOp)
		}
	case 29:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:161
		{
			exprVAL.UnwrapExpr = exprDollar[1].UnwrapExpr.addPostFilter(exprDollar[3].LabelFilter)
		}
	case 30:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:165
		{
			exprVAL.ConvOp = OpConvBytes
		}
	case 31:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:166
		{
			exprVAL.ConvOp = OpConvDuration
		}
	case 32:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:167
		{
			exprVAL.ConvOp = OpConvDurationSeconds
		}
	case 33:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:171
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[3].LogRangeExpr, exprDollar[1].RangeOp, nil, nil)
		}
	case 34:
		exprDollar = exprS[exprpt-6 : exprpt+1]
//line pkg/logql/expr.y:172
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[5].LogRangeExpr, exprDollar[1].RangeOp, nil, &exprDollar[3].str)
		}
	case 35:
		exprDollar = exprS[exprpt-5 : exprpt+1]
//line pkg/logql/expr.y:173
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[3].LogRangeExpr, exprDollar[1].RangeOp, exprDollar[5].Grouping, nil)
		}
	case 36:
		exprDollar = exprS[exprpt-7 : exprpt+1]
//line pkg/logql/expr.y:174
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[5].LogRangeExpr, exprDollar[1].RangeOp, exprDollar[7].Grouping, &exprDollar[3].str)
		}
	case 37:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:179
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[3].MetricExpr, exprDollar[1].VectorOp, nil, nil)
		}
	case 38:
		exprDollar = exprS[exprpt-5 : exprpt+1]
//line pkg/logql/expr.y:180
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[4].MetricExpr, exprDollar[1].VectorOp, exprDollar[2].Grouping, nil)
		}
	case 39:
		exprDollar = exprS[exprpt-5 : exprpt+1]
//line pkg/logql/expr.y:181
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[3].MetricExpr, exprDollar[1].VectorOp, exprDollar[5].Grouping, nil)
		}
	case 40:
		exprDollar = exprS[exprpt-6 : exprpt+1]
//line pkg/logql/expr.y:183
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[5].MetricExpr, exprDollar[1].VectorOp, nil, &exprDollar[3].str)
		}
	case 41:
		exprDollar = exprS[exprpt-7 : exprpt+1]
//line pkg/logql/expr.y:184
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[5].MetricExpr, exprDollar[1].VectorOp, exprDollar[7].Grouping, &exprDollar[3].str)
		}
	case 42:
		exprDollar = exprS[exprpt-7 : exprpt+1]
//line pkg/logql/expr.y:185
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[6].MetricExpr, exprDollar[1].VectorOp, exprDollar[2].Grouping, &exprDollar[4].str)
		}
	case 43:
		exprDollar = exprS[exprpt-12 : exprpt+1]
//line pkg/logql/expr.y:190
		{
			exprVAL.LabelReplaceExpr = mustNewLabelReplaceExpr(exprDollar[3].MetricExpr, exprDollar[5].str, exprDollar[7].str, exprDollar[9].str, exprDollar[11].str)
		}
	case 44:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:194
		{
			exprVAL.Filter = labels.MatchRegexp
		}
	case 45:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:195
		{
			exprVAL.Filter = labels.MatchEqual
		}
	case 46:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:196
		{
			exprVAL.Filter = labels.MatchNotRegexp
		}
	case 47:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:197
		{
			exprVAL.Filter = labels.MatchNotEqual
		}
	case 48:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:201
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 49:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:202
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 50:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:203
		{
		}
	case 51:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:207
		{
			exprVAL.Matchers = []*labels.Matcher{exprDollar[1].Matcher}
		}
	case 52:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:208
		{
			exprVAL.Matchers = append(exprDollar[1].Matchers, exprDollar[3].Matcher)
		}
	case 53:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:212
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 54:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:213
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchNotEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 55:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:214
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 56:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:215
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchNotRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 57:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:219
		{
			exprVAL.PipelineExpr = MultiStageExpr{exprDollar[1].PipelineStage}
		}
	case 58:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:220
		{
			exprVAL.PipelineExpr = append(exprDollar[1].PipelineExpr, exprDollar[2].PipelineStage)
		}
	case 59:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:224
		{
			exprVAL.PipelineStage = exprDollar[1].LineFilters
		}
	case 60:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:225
		{
			exprVAL.PipelineStage = exprDollar[2].LabelParser
		}
	case 61:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:226
		{
			exprVAL.PipelineStage = exprDollar[2].JSONExpressionParser
		}
	case 62:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:227
		{
			exprVAL.PipelineStage = &labelFilterExpr{LabelFilterer: exprDollar[2].LabelFilter}
		}
	case 63:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:228
		{
			exprVAL.PipelineStage = exprDollar[2].LineFormatExpr
		}
	case 64:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:229
		{
			exprVAL.PipelineStage = exprDollar[2].LabelFormatExpr
		}
	case 65:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:230
		{
			exprVAL.PipelineStage = exprDollar[2].DropLabelsExpr
		}
	case 66:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:234
		{
			exprVAL.LineFilters = newLineFilterExpr(nil, exprDollar[1].Filter, exprDollar[2].str)
		}
	case 67:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:235
		{
			exprVAL.LineFilters = newLineFilterExpr(exprDollar[1].LineFilters, exprDollar[2].Filter, exprDollar[3].str)
		}
	case 68:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:238
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeJSON, "")
		}
	case 69:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:239
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeLogfmt, "")
		}
	case 70:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:240
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeRegexp, exprDollar[2].str)
		}
	case 71:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:241
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypePattern, exprDollar[2].str)
		}
	case 72:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:242
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeUnpack, "")
		}
	case 73:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:246
		{
			exprVAL.JSONExpressionParser = newJSONExpressionParser(exprDollar[2].JSONExpressionList)
		}
	case 74:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:248
		{
			exprVAL.LineFormatExpr = newLineFmtExpr(exprDollar[2].str)
		}
	case 75:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:251
		{
			exprVAL.LabelFormat = log.NewRenameLabelFmt(exprDollar[1].str, exprDollar[3].str)
		}
	case 76:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:252
		{
			exprVAL.LabelFormat = log.NewTemplateLabelFmt(exprDollar[1].str, exprDollar[3].str)
		}
	case 77:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:256
		{
			exprVAL.LabelsFormat = []log.LabelFmt{exprDollar[1].LabelFormat}
		}
	case 78:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:257
		{
			exprVAL.LabelsFormat = append(exprDollar[1].LabelsFormat, exprDollar[3].LabelFormat)
		}
	case 80:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:261
		{
			exprVAL.LabelFormatExpr = newLabelFmtExpr(exprDollar[2].LabelsFormat)
		}
	case 81:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:264
		{
			exprVAL.LabelFilter = log.NewStringLabelFilter(exprDollar[1].Matcher)
		}
	case 82:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:265
		{
			exprVAL.LabelFilter = exprDollar[1].UnitFilter
		}
	case 83:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:266
		{
			exprVAL.LabelFilter = exprDollar[1].NumberFilter
		}
	case 84:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:267
		{
			exprVAL.LabelFilter = exprDollar[2].LabelFilter
		}
	case 85:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:268
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[2].LabelFilter)
		}
	case 86:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:269
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 87:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:270
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 88:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:271
		{
			exprVAL.LabelFilter = log.NewOrLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 89:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:275
		{
			exprVAL.JSONExpression = log.NewJSONExpr(exprDollar[1].str, exprDollar[3].str)
		}
	case 90:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:278
		{
			exprVAL.JSONExpressionList = []log.JSONExpression{exprDollar[1].JSONExpression}
		}
	case 91:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:279
		{
			exprVAL.JSONExpressionList = append(exprDollar[1].JSONExpressionList, exprDollar[3].JSONExpression)
		}
	case 92:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:283
		{
			exprVAL.UnitFilter = exprDollar[1].DurationFilter
		}
	case 93:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:284
		{
			exprVAL.UnitFilter = exprDollar[1].BytesFilter
		}
	case 94:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:287
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, exprDollar[3].duration)
		}
	case 95:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:288
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 96:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:289
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, exprDollar[3].duration)
		}
	case 97:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:290
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 98:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:291
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 99:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:292
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 100:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:293
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 101:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:297
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 102:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:298
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 103:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:299
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 104:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:300
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 105:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:301
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 106:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:302
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 107:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:303
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 108:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:307
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 109:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:308
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 110:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:309
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 111:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:310
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 112:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:311
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 113:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:312
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 114:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:313
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 115:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:317
		{
			exprVAL.DropLabel = log.NewDropLabel(nil, exprDollar[1].str)
		}
	case 116:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:318
		{
			exprVAL.DropLabel = log.NewDropLabel(exprDollar[1].Matcher, "")
		}
	case 117:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:321
		{
			exprVAL.DropLabels = []log.DropLabel{exprDollar[1].DropLabel}
		}
	case 118:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:322
		{
			exprVAL.DropLabels = append(exprDollar[1].DropLabels, exprDollar[3].DropLabel)
		}
	case 119:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:325
		{
			exprVAL.DropLabelsExpr = newDropLabelsExpr(exprDollar[2].DropLabels)
		}
	case 120:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:330
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("or", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 121:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:331
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("and", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 122:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:332
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("unless", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 123:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:333
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("+", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 124:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:334
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("-", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 125:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:335
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("*", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 126:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:336
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("/", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 127:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:337
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("%", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 128:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:338
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("^", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 129:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:339
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("==", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 130:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:340
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("!=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 131:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:341
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr(">", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 132:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:342
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr(">=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 133:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:343
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("<", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 134:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:344
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("<=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 135:
		exprDollar = exprS[exprpt-0 : exprpt+1]
//line pkg/logql/expr.y:348
		{
			exprVAL.BinOpModifier = BinOpOptions{}
		}
	case 136:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:349
		{
			exprVAL.BinOpModifier = BinOpOptions{ReturnBool: true}
		}
	case 137:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:353
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[1].str, false)
		}
	case 138:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:354
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[2].str, false)
		}
	case 139:
		exprDollar = exprS[exprpt-2 : exprpt+1]
//line pkg/logql/expr.y:355
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[2].str, true)
		}
	case 140:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:359
		{
			exprVAL.VectorOp = OpTypeSum
		}
	case 141:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:360
		{
			exprVAL.VectorOp = OpTypeAvg
		}
	case 142:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:361
		{
			exprVAL.VectorOp = OpTypeCount
		}
	case 143:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:362
		{
			exprVAL.VectorOp = OpTypeMax
		}
	case 144:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:363
		{
			exprVAL.VectorOp = OpTypeMin
		}
	case 145:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:364
		{
			exprVAL.VectorOp = OpTypeStddev
		}
	case 146:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:365
		{
			exprVAL.VectorOp = OpTypeStdvar
		}
	case 147:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:366
		{
			exprVAL.VectorOp = OpTypeBottomK
		}
	case 148:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:367
		{
			exprVAL.VectorOp = OpTypeTopK
		}
	case 149:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:371
		{
			exprVAL.RangeOp = OpRangeTypeCount
		}
	case 150:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:372
		{
			exprVAL.RangeOp = OpRangeTypeRate
		}
	case 151:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:373
		{
			exprVAL.RangeOp = OpRangeTypeBytes
		}
	case 152:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:374
		{
			exprVAL.RangeOp = OpRangeTypeBytesRate
		}
	case 153:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:375
		{
			exprVAL.RangeOp = OpRangeTypeAvg
		}
	case 154:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:376
		{
			exprVAL.RangeOp = OpRangeTypeSum
		}
	case 155:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:377
		{
			exprVAL.RangeOp = OpRangeTypeMin
		}
	case 156:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:378
		{
			exprVAL.RangeOp = OpRangeTypeMax
		}
	case 157:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:379
		{
			exprVAL.RangeOp = OpRangeTypeStdvar
		}
	case 158:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:380
		{
			exprVAL.RangeOp = OpRangeTypeStddev
		}
	case 159:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:381
		{
			exprVAL.RangeOp = OpRangeTypeQuantile
		}
	case 160:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:382
		{
			exprVAL.RangeOp = OpRangeTypeAbsent
		}
	case 161:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line pkg/logql/expr.y:387
		{
			exprVAL.Labels = []string{exprDollar[1].str}
		}
	case 162:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:388
		{
			exprVAL.Labels = append(exprDollar[1].Labels, exprDollar[3].str)
		}
	case 163:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:392
		{
			exprVAL.Grouping = &grouping{without: false, groups: exprDollar[3].Labels}
		}
	case 164:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line pkg/logql/expr.y:393
		{
			exprVAL.Grouping = &grouping{without: true, groups: exprDollar[3].Labels}
		}
	case 165:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:394
		{
			exprVAL.Grouping = &grouping{without: false, groups: nil}
		}
	case 166:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line pkg/logql/expr.y:395
		{
			exprVAL.Grouping = &grouping{without: true, groups: nil}
		}
	}
	goto exprstack /* stack new state and value */
}
