version: "2"
linters:
  enable:
    - staticcheck
    - lll
    - revive
    - govet
    - errcheck
    - ineffassign
    - unused

  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - ".*.pb.go"
      - ".*.y.go"
