version: "2"
linters:
  enable:
    - staticcheck
    - lll
    - revive
    - govet
    - errcheck
    - ineffassign
    - unused
    - misspell

  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - ".*.pb.go"
      - ".*.y.go"
formatters:
  settings:
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines    
