// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: logproto/logproto.proto

package logproto

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_FORWARD  Direction = 0
	Direction_BACKWARD Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "FORWARD",
		1: "BACKWARD",
	}
	Direction_value = map[string]int32{
		"FORWARD":  0,
		"BACKWARD": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_logproto_logproto_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_logproto_logproto_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{0}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Direction     Direction              `protobuf:"varint,5,opt,name=direction,proto3,enum=logproto.Direction" json:"direction,omitempty"`
	Shards        []string               `protobuf:"bytes,7,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_logproto_logproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *QueryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *QueryRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *QueryRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_FORWARD
}

func (x *QueryRequest) GetShards() []string {
	if x != nil {
		return x.Shards
	}
	return nil
}

type SampleQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Shards        []string               `protobuf:"bytes,4,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleQueryRequest) Reset() {
	*x = SampleQueryRequest{}
	mi := &file_logproto_logproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleQueryRequest) ProtoMessage() {}

func (x *SampleQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleQueryRequest.ProtoReflect.Descriptor instead.
func (*SampleQueryRequest) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{1}
}

func (x *SampleQueryRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SampleQueryRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SampleQueryRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *SampleQueryRequest) GetShards() []string {
	if x != nil {
		return x.Shards
	}
	return nil
}

type SampleQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleQueryResponse) Reset() {
	*x = SampleQueryResponse{}
	mi := &file_logproto_logproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleQueryResponse) ProtoMessage() {}

func (x *SampleQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleQueryResponse.ProtoReflect.Descriptor instead.
func (*SampleQueryResponse) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{2}
}

func (x *SampleQueryResponse) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamAdapter       `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_logproto_logproto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetStreams() []*StreamAdapter {
	if x != nil {
		return x.Streams
	}
	return nil
}

type LabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        bool                   `protobuf:"varint,2,opt,name=values,proto3" json:"values,omitempty"` // True to fetch label values, false for fetch labels names.
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelRequest) Reset() {
	*x = LabelRequest{}
	mi := &file_logproto_logproto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelRequest) ProtoMessage() {}

func (x *LabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelRequest.ProtoReflect.Descriptor instead.
func (*LabelRequest) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{4}
}

func (x *LabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelRequest) GetValues() bool {
	if x != nil {
		return x.Values
	}
	return false
}

func (x *LabelRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *LabelRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *LabelRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type LabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelResponse) Reset() {
	*x = LabelResponse{}
	mi := &file_logproto_logproto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelResponse) ProtoMessage() {}

func (x *LabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelResponse.ProtoReflect.Descriptor instead.
func (*LabelResponse) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{5}
}

func (x *LabelResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type StreamAdapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        string                 `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	Entries       []*EntryAdapter        `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAdapter) Reset() {
	*x = StreamAdapter{}
	mi := &file_logproto_logproto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAdapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAdapter) ProtoMessage() {}

func (x *StreamAdapter) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAdapter.ProtoReflect.Descriptor instead.
func (*StreamAdapter) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{6}
}

func (x *StreamAdapter) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *StreamAdapter) GetEntries() []*EntryAdapter {
	if x != nil {
		return x.Entries
	}
	return nil
}

type EntryAdapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryAdapter) Reset() {
	*x = EntryAdapter{}
	mi := &file_logproto_logproto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryAdapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryAdapter) ProtoMessage() {}

func (x *EntryAdapter) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryAdapter.ProtoReflect.Descriptor instead.
func (*EntryAdapter) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{7}
}

func (x *EntryAdapter) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EntryAdapter) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Hash          uint64                 `protobuf:"varint,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_logproto_logproto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{8}
}

func (x *Sample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Sample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sample) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        string                 `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	Samples       []*Sample              `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_logproto_logproto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{9}
}

func (x *Series) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *Series) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type TailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	DelayFor      uint32                 `protobuf:"varint,3,opt,name=delayFor,proto3" json:"delayFor,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailRequest) Reset() {
	*x = TailRequest{}
	mi := &file_logproto_logproto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailRequest) ProtoMessage() {}

func (x *TailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailRequest.ProtoReflect.Descriptor instead.
func (*TailRequest) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{10}
}

func (x *TailRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TailRequest) GetDelayFor() uint32 {
	if x != nil {
		return x.DelayFor
	}
	return 0
}

func (x *TailRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TailRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

type TailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Stream         *StreamAdapter         `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	DroppedStreams []*DroppedStream       `protobuf:"bytes,2,rep,name=droppedStreams,proto3" json:"droppedStreams,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TailResponse) Reset() {
	*x = TailResponse{}
	mi := &file_logproto_logproto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailResponse) ProtoMessage() {}

func (x *TailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailResponse.ProtoReflect.Descriptor instead.
func (*TailResponse) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{11}
}

func (x *TailResponse) GetStream() *StreamAdapter {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *TailResponse) GetDroppedStreams() []*DroppedStream {
	if x != nil {
		return x.DroppedStreams
	}
	return nil
}

type SeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Groups        []string               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesRequest) Reset() {
	*x = SeriesRequest{}
	mi := &file_logproto_logproto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesRequest) ProtoMessage() {}

func (x *SeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesRequest.ProtoReflect.Descriptor instead.
func (*SeriesRequest) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{12}
}

func (x *SeriesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SeriesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *SeriesRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type SeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*SeriesIdentifier    `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesResponse) Reset() {
	*x = SeriesResponse{}
	mi := &file_logproto_logproto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesResponse) ProtoMessage() {}

func (x *SeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesResponse.ProtoReflect.Descriptor instead.
func (*SeriesResponse) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{13}
}

func (x *SeriesResponse) GetSeries() []*SeriesIdentifier {
	if x != nil {
		return x.Series
	}
	return nil
}

type SeriesIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesIdentifier) Reset() {
	*x = SeriesIdentifier{}
	mi := &file_logproto_logproto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesIdentifier) ProtoMessage() {}

func (x *SeriesIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesIdentifier.ProtoReflect.Descriptor instead.
func (*SeriesIdentifier) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{14}
}

func (x *SeriesIdentifier) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DroppedStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Labels        string                 `protobuf:"bytes,3,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroppedStream) Reset() {
	*x = DroppedStream{}
	mi := &file_logproto_logproto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroppedStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroppedStream) ProtoMessage() {}

func (x *DroppedStream) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroppedStream.ProtoReflect.Descriptor instead.
func (*DroppedStream) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{15}
}

func (x *DroppedStream) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DroppedStream) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *DroppedStream) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

type TimeSeriesChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromIngesterId string                 `protobuf:"bytes,1,opt,name=from_ingester_id,json=fromIngesterId,proto3" json:"from_ingester_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Labels         []*LabelPair           `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Chunks         []*Chunk               `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimeSeriesChunk) Reset() {
	*x = TimeSeriesChunk{}
	mi := &file_logproto_logproto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesChunk) ProtoMessage() {}

func (x *TimeSeriesChunk) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesChunk.ProtoReflect.Descriptor instead.
func (*TimeSeriesChunk) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{16}
}

func (x *TimeSeriesChunk) GetFromIngesterId() string {
	if x != nil {
		return x.FromIngesterId
	}
	return ""
}

func (x *TimeSeriesChunk) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TimeSeriesChunk) GetLabels() []*LabelPair {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TimeSeriesChunk) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type LabelPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelPair) Reset() {
	*x = LabelPair{}
	mi := &file_logproto_logproto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelPair) ProtoMessage() {}

func (x *LabelPair) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelPair.ProtoReflect.Descriptor instead.
func (*LabelPair) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{17}
}

func (x *LabelPair) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_logproto_logproto_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{18}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TransferChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferChunksResponse) Reset() {
	*x = TransferChunksResponse{}
	mi := &file_logproto_logproto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferChunksResponse) ProtoMessage() {}

func (x *TransferChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferChunksResponse.ProtoReflect.Descriptor instead.
func (*TransferChunksResponse) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{19}
}

type TailersCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailersCountRequest) Reset() {
	*x = TailersCountRequest{}
	mi := &file_logproto_logproto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailersCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailersCountRequest) ProtoMessage() {}

func (x *TailersCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailersCountRequest.ProtoReflect.Descriptor instead.
func (*TailersCountRequest) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{20}
}

type TailersCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailersCountResponse) Reset() {
	*x = TailersCountResponse{}
	mi := &file_logproto_logproto_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailersCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailersCountResponse) ProtoMessage() {}

func (x *TailersCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logproto_logproto_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailersCountResponse.ProtoReflect.Descriptor instead.
func (*TailersCountResponse) Descriptor() ([]byte, []int) {
	return file_logproto_logproto_proto_rawDescGZIP(), []int{21}
}

func (x *TailersCountResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_logproto_logproto_proto protoreflect.FileDescriptor

const file_logproto_logproto_proto_rawDesc = "" +
	"\n" +
	"\x17logproto/logproto.proto\x12\blogproto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rpb/gogo.proto\"\x9b\x02\n" +
	"\fQueryRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12:\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x05start\x126\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x03end\x121\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x13.logproto.DirectionR\tdirection\x12,\n" +
	"\x06shards\x18\a \x03(\tB\x14\xea\xde\x1f\x10shards,omitemptyR\x06shardsJ\x04\b\x06\x10\a\"\xd2\x01\n" +
	"\x12SampleQueryRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12:\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x05start\x126\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x03end\x12,\n" +
	"\x06shards\x18\x04 \x03(\tB\x14\xea\xde\x1f\x10shards,omitemptyR\x06shards\"O\n" +
	"\x13SampleQueryResponse\x128\n" +
	"\x06series\x18\x01 \x03(\v2\x10.logproto.SeriesB\x0e\xc8\xde\x1f\x01\xda\xde\x1f\x06SeriesR\x06series\"R\n" +
	"\rQueryResponse\x12A\n" +
	"\astreams\x18\x01 \x03(\v2\x17.logproto.StreamAdapterB\x0e\xc8\xde\x1f\x01\xda\xde\x1f\x06StreamR\astreams\"\xc4\x01\n" +
	"\fLabelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x01(\bR\x06values\x12:\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x01\x90\xdf\x1f\x01R\x05start\x126\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x01\x90\xdf\x1f\x01R\x03end\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\"'\n" +
	"\rLabelResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"v\n" +
	"\rStreamAdapter\x12\"\n" +
	"\x06labels\x18\x01 \x01(\tB\n" +
	"\xea\xde\x1f\x06labelsR\x06labels\x12A\n" +
	"\aentries\x18\x02 \x03(\v2\x16.logproto.EntryAdapterB\x0f\xc8\xde\x1f\x00\xea\xde\x1f\aentriesR\aentries\"v\n" +
	"\fEntryAdapter\x12H\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x0e\xc8\xde\x1f\x00\xea\xde\x1f\x02ts\x90\xdf\x1f\x01R\ttimestamp\x12\x1c\n" +
	"\x04line\x18\x02 \x01(\tB\b\xea\xde\x1f\x04lineR\x04line\"m\n" +
	"\x06Sample\x12$\n" +
	"\ttimestamp\x18\x01 \x01(\x03B\x06\xea\xde\x1f\x02tsR\ttimestamp\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\x01B\t\xea\xde\x1f\x05valueR\x05value\x12\x1c\n" +
	"\x04hash\x18\x03 \x01(\x04B\b\xea\xde\x1f\x04hashR\x04hash\"i\n" +
	"\x06Series\x12\"\n" +
	"\x06labels\x18\x01 \x01(\tB\n" +
	"\xea\xde\x1f\x06labelsR\x06labels\x12;\n" +
	"\asamples\x18\x02 \x03(\v2\x10.logproto.SampleB\x0f\xc8\xde\x1f\x00\xea\xde\x1f\asamplesR\asamples\"\x97\x01\n" +
	"\vTailRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bdelayFor\x18\x03 \x01(\rR\bdelayFor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12:\n" +
	"\x05start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x05startJ\x04\b\x02\x10\x03\"\x8c\x01\n" +
	"\fTailResponse\x12;\n" +
	"\x06stream\x18\x01 \x01(\v2\x17.logproto.StreamAdapterB\n" +
	"\xda\xde\x1f\x06StreamR\x06stream\x12?\n" +
	"\x0edroppedStreams\x18\x02 \x03(\v2\x17.logproto.DroppedStreamR\x0edroppedStreams\"\x9b\x01\n" +
	"\rSeriesRequest\x12:\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x05start\x126\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x03end\x12\x16\n" +
	"\x06groups\x18\x03 \x03(\tR\x06groups\"J\n" +
	"\x0eSeriesResponse\x128\n" +
	"\x06series\x18\x01 \x03(\v2\x1a.logproto.SeriesIdentifierB\x04\xc8\xde\x1f\x00R\x06series\"\x8d\x01\n" +
	"\x10SeriesIdentifier\x12>\n" +
	"\x06labels\x18\x01 \x03(\v2&.logproto.SeriesIdentifier.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\rDroppedStream\x128\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x04from\x124\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x02to\x12\x16\n" +
	"\x06labels\x18\x03 \x01(\tR\x06labels\"\xaa\x01\n" +
	"\x0fTimeSeriesChunk\x12(\n" +
	"\x10from_ingester_id\x18\x01 \x01(\tR\x0efromIngesterId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x06labels\x18\x03 \x03(\v2\x13.logproto.LabelPairR\x06labels\x12'\n" +
	"\x06chunks\x18\x04 \x03(\v2\x0f.logproto.ChunkR\x06chunks\"5\n" +
	"\tLabelPair\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1b\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x18\n" +
	"\x16TransferChunksResponse\"\x15\n" +
	"\x13TailersCountRequest\",\n" +
	"\x14TailersCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count*&\n" +
	"\tDirection\x12\v\n" +
	"\aFORWARD\x10\x00\x12\f\n" +
	"\bBACKWARD\x10\x012\x9e\x03\n" +
	"\aQuerier\x12<\n" +
	"\x05Query\x12\x16.logproto.QueryRequest\x1a\x17.logproto.QueryResponse\"\x000\x01\x12N\n" +
	"\vQuerySample\x12\x1c.logproto.SampleQueryRequest\x1a\x1d.logproto.SampleQueryResponse\"\x000\x01\x12:\n" +
	"\x05Label\x12\x16.logproto.LabelRequest\x1a\x17.logproto.LabelResponse\"\x00\x129\n" +
	"\x04Tail\x12\x15.logproto.TailRequest\x1a\x16.logproto.TailResponse\"\x000\x01\x12=\n" +
	"\x06Series\x12\x17.logproto.SeriesRequest\x1a\x18.logproto.SeriesResponse\"\x00\x12O\n" +
	"\fTailersCount\x12\x1d.logproto.TailersCountRequest\x1a\x1e.logproto.TailersCountResponse\"\x002]\n" +
	"\bIngester\x12Q\n" +
	"\x0eTransferChunks\x12\x19.logproto.TimeSeriesChunk\x1a .logproto.TransferChunksResponse\"\x00(\x01B!Z\x1fgithub.com/ronanh/loki/logprotob\x06proto3"

var (
	file_logproto_logproto_proto_rawDescOnce sync.Once
	file_logproto_logproto_proto_rawDescData []byte
)

func file_logproto_logproto_proto_rawDescGZIP() []byte {
	file_logproto_logproto_proto_rawDescOnce.Do(func() {
		file_logproto_logproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logproto_logproto_proto_rawDesc), len(file_logproto_logproto_proto_rawDesc)))
	})
	return file_logproto_logproto_proto_rawDescData
}

var file_logproto_logproto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logproto_logproto_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_logproto_logproto_proto_goTypes = []any{
	(Direction)(0),                 // 0: logproto.Direction
	(*QueryRequest)(nil),           // 1: logproto.QueryRequest
	(*SampleQueryRequest)(nil),     // 2: logproto.SampleQueryRequest
	(*SampleQueryResponse)(nil),    // 3: logproto.SampleQueryResponse
	(*QueryResponse)(nil),          // 4: logproto.QueryResponse
	(*LabelRequest)(nil),           // 5: logproto.LabelRequest
	(*LabelResponse)(nil),          // 6: logproto.LabelResponse
	(*StreamAdapter)(nil),          // 7: logproto.StreamAdapter
	(*EntryAdapter)(nil),           // 8: logproto.EntryAdapter
	(*Sample)(nil),                 // 9: logproto.Sample
	(*Series)(nil),                 // 10: logproto.Series
	(*TailRequest)(nil),            // 11: logproto.TailRequest
	(*TailResponse)(nil),           // 12: logproto.TailResponse
	(*SeriesRequest)(nil),          // 13: logproto.SeriesRequest
	(*SeriesResponse)(nil),         // 14: logproto.SeriesResponse
	(*SeriesIdentifier)(nil),       // 15: logproto.SeriesIdentifier
	(*DroppedStream)(nil),          // 16: logproto.DroppedStream
	(*TimeSeriesChunk)(nil),        // 17: logproto.TimeSeriesChunk
	(*LabelPair)(nil),              // 18: logproto.LabelPair
	(*Chunk)(nil),                  // 19: logproto.Chunk
	(*TransferChunksResponse)(nil), // 20: logproto.TransferChunksResponse
	(*TailersCountRequest)(nil),    // 21: logproto.TailersCountRequest
	(*TailersCountResponse)(nil),   // 22: logproto.TailersCountResponse
	nil,                            // 23: logproto.SeriesIdentifier.LabelsEntry
	(*timestamppb.Timestamp)(nil),  // 24: google.protobuf.Timestamp
}
var file_logproto_logproto_proto_depIdxs = []int32{
	24, // 0: logproto.QueryRequest.start:type_name -> google.protobuf.Timestamp
	24, // 1: logproto.QueryRequest.end:type_name -> google.protobuf.Timestamp
	0,  // 2: logproto.QueryRequest.direction:type_name -> logproto.Direction
	24, // 3: logproto.SampleQueryRequest.start:type_name -> google.protobuf.Timestamp
	24, // 4: logproto.SampleQueryRequest.end:type_name -> google.protobuf.Timestamp
	10, // 5: logproto.SampleQueryResponse.series:type_name -> logproto.Series
	7,  // 6: logproto.QueryResponse.streams:type_name -> logproto.StreamAdapter
	24, // 7: logproto.LabelRequest.start:type_name -> google.protobuf.Timestamp
	24, // 8: logproto.LabelRequest.end:type_name -> google.protobuf.Timestamp
	8,  // 9: logproto.StreamAdapter.entries:type_name -> logproto.EntryAdapter
	24, // 10: logproto.EntryAdapter.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 11: logproto.Series.samples:type_name -> logproto.Sample
	24, // 12: logproto.TailRequest.start:type_name -> google.protobuf.Timestamp
	7,  // 13: logproto.TailResponse.stream:type_name -> logproto.StreamAdapter
	16, // 14: logproto.TailResponse.droppedStreams:type_name -> logproto.DroppedStream
	24, // 15: logproto.SeriesRequest.start:type_name -> google.protobuf.Timestamp
	24, // 16: logproto.SeriesRequest.end:type_name -> google.protobuf.Timestamp
	15, // 17: logproto.SeriesResponse.series:type_name -> logproto.SeriesIdentifier
	23, // 18: logproto.SeriesIdentifier.labels:type_name -> logproto.SeriesIdentifier.LabelsEntry
	24, // 19: logproto.DroppedStream.from:type_name -> google.protobuf.Timestamp
	24, // 20: logproto.DroppedStream.to:type_name -> google.protobuf.Timestamp
	18, // 21: logproto.TimeSeriesChunk.labels:type_name -> logproto.LabelPair
	19, // 22: logproto.TimeSeriesChunk.chunks:type_name -> logproto.Chunk
	1,  // 23: logproto.Querier.Query:input_type -> logproto.QueryRequest
	2,  // 24: logproto.Querier.QuerySample:input_type -> logproto.SampleQueryRequest
	5,  // 25: logproto.Querier.Label:input_type -> logproto.LabelRequest
	11, // 26: logproto.Querier.Tail:input_type -> logproto.TailRequest
	13, // 27: logproto.Querier.Series:input_type -> logproto.SeriesRequest
	21, // 28: logproto.Querier.TailersCount:input_type -> logproto.TailersCountRequest
	17, // 29: logproto.Ingester.TransferChunks:input_type -> logproto.TimeSeriesChunk
	4,  // 30: logproto.Querier.Query:output_type -> logproto.QueryResponse
	3,  // 31: logproto.Querier.QuerySample:output_type -> logproto.SampleQueryResponse
	6,  // 32: logproto.Querier.Label:output_type -> logproto.LabelResponse
	12, // 33: logproto.Querier.Tail:output_type -> logproto.TailResponse
	14, // 34: logproto.Querier.Series:output_type -> logproto.SeriesResponse
	22, // 35: logproto.Querier.TailersCount:output_type -> logproto.TailersCountResponse
	20, // 36: logproto.Ingester.TransferChunks:output_type -> logproto.TransferChunksResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_logproto_logproto_proto_init() }
func file_logproto_logproto_proto_init() {
	if File_logproto_logproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logproto_logproto_proto_rawDesc), len(file_logproto_logproto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_logproto_logproto_proto_goTypes,
		DependencyIndexes: file_logproto_logproto_proto_depIdxs,
		EnumInfos:         file_logproto_logproto_proto_enumTypes,
		MessageInfos:      file_logproto_logproto_proto_msgTypes,
	}.Build()
	File_logproto_logproto_proto = out.File
	file_logproto_logproto_proto_goTypes = nil
	file_logproto_logproto_proto_depIdxs = nil
}
